### PR TITLE
add support for https protocol and endpoint prefixes in the URL to ac…

### PR DESCRIPTION
**Pull request by nicodv**
…commodate, for example, kubernetes deployments

### CODE REVIEW

**Comment by nicodv** [comment]
@scarchik , I am using `opentsdb-py` with a kubernetes deployment of OpenTSDB. This had https enabled and a custom endpoint, so I needed to remove some of the hardcoded URL settings.

**Comment by scarchik** [comment]
@nicodv, thanks for PR.

I belive that it will be better to merge all this parameters  (host, port, protocol and endpoint) to one mandatory parameter like OPEN_TSDB_URI.

**Comment by nicodv** [comment]
That makes sense, @scarchik . Would you want to deprecate the old params (host, port), or keep backward compatibility?

**Comment by nicodv** [comment]
OK, I left it backward compatible and just introduced an optional uri argument. Indeed it's much cleaner now.

Let me know what you think, @scarchik .

**Comment by scarchik** [comment]
Looks really good. Thank you, @nicodv!

**Pull request merged**
